server:
    port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/nextgadget_users
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 2N+vHTiJ3eQeBxxoA+YP0rHNsLjquQQnpOYkE9fQIbOQwR4Wzx9Q+0iW+n5wXz+f7pHoRd5Q8axqGvg6yWQFZkg==
  expiration: 3600000
