INSERT INTO products (name, category, price, stock, image_url) VALUES
  ('Android TV', 'TV and Video', 499.99, 20, 'https://i.imgur.com/uLTGMoM.png'),
  ('HD Flatscreen TV', 'TV and Video', 399.99, 15, 'https://i.imgur.com/LEpzxEp.png'),
  ('Vintage TV', 'TV and Video', 250.00, 5, 'https://i.imgur.com/2NMGoeI.png'),
  ('Samsung TV', 'TV and Video', 799.99, 10, 'https://i.imgur.com/LYdbrYg.png'),
  ('Apple iMac', 'Computers', 1299.99, 8, 'https://i.imgur.com/BjYMIVz.png'),
  ('Dell Laptop', 'Computers', 899.99, 12, 'https://i.imgur.com/JwrUP8P.png'),
  ('Microsoft Surface', 'Computers', 999.99, 10, 'https://i.imgur.com/4ILXOhL.png'),
  ('MacBook Pro', 'Computers', 1499.99, 7, 'https://i.imgur.com/9HFAm8V.png'),
  ('Black Wireless Headphones', 'Audio', 199.99, 25, 'https://i.imgur.com/3CJEEsL.png'),
  ('Gray Wireless Headphones', 'Audio', 179.99, 30, 'https://i.imgur.com/EpqdTMw.png'),
  ('Pink Wireless Beats', 'Audio', 219.99, 20, 'https://i.imgur.com/QYM8aU8.png'),
  ('Apple Air Pods', 'Audio', 249.99, 18, 'https://i.imgur.com/M0Hb63J.png'),
  ('Xbox One', 'Gaming', 299.99, 15, 'https://i.imgur.com/F2YMA70.png'),
  ('PlayStation 5', 'Gaming', 499.99, 10, 'https://i.imgur.com/syRN0IT.png'),
  ('Nintendo Switch', 'Gaming', 299.99, 14, 'https://i.imgur.com/B62QSTU.png'),
  ('Xbox & PlayStation Controllers', 'Gaming', 59.99, 40, 'https://i.imgur.com/csNQI2B.png'),
  ('iPhone X', 'Phones', 699.99, 20, 'https://i.imgur.com/BSrSmTp.png'),
  ('Samsung Galaxy', 'Phones', 799.99, 18, 'https://i.imgur.com/L1biU7Y.png'),
  ('Sony Android', 'Phones', 599.99, 25, 'https://i.imgur.com/9xOdubM.png'),
  ('Vintage Rotary Phone', 'Phones', 120.00, 7, 'https://i.imgur.com/iTIYq1m.png');
